CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat FLOAT                                   NOT NULL,
    lon FLOAT                                   NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                 VARCHAR(255)                            NOT NULL,
    description           VARCHAR(512)                            NOT NULL,
    application           VARCHAR(512)                            NOT NULL,
    is_request_moderation BOOLEAN                                 NOT NULL,
    initiator_id          INT                                     NOT NULL,
    category_id           INT                                     NOT NULL,
    is_paid               BOOLEAN                                 NOT NULL,
    created               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_date            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    published_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    state                 VARCHAR(255)                            NOT NULL,
    location_id           INT                                     NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_event_on_author FOREIGN KEY (initiator_id) REFERENCES users (id),
    CONSTRAINT fk_event_on_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_event_on_location FOREIGN KEY (location_id) REFERENCES locations (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(4000)                           NOT NULL,
    requester_id INT                                     NOT NULL,
    event_id     INT                                     NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_request_on_requester FOREIGN KEY (requester_id) REFERENCES users (id),
    CONSTRAINT fk_request_on_event FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(255)                            NOT NULL,
    is_pinned BOOLEAN                                 NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_compilations
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id       INT                                     NOT NULL,
    compilation_id INT                                     NOT NULL,
    created        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_event_compilations PRIMARY KEY (id),
    CONSTRAINT fk_event_compilations_on_event FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_event_compilations_on_compilations FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);
