CREATE TABLE IF NOT EXISTS event_statistics
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id  INT                                     NOT NULL,
    author_id INT                                     NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_event_statistics PRIMARY KEY (id),
);

CREATE TABLE IF NOT EXISTS list_statistics
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    criterion VARCHAR(255)                            NOT NULL,
    author_id INT                                     NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
);